# Deprecated, must be deleted.
arb-dir: lib/src/common/localization/translations
template-arb-file: intl_ru.arb
output-localization-file: generated_localizations.dart
output-class: GeneratedLocalizations
nullable-getter: false