name: ln_employee
description: >
  Bla bla bla

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Localizations
  intl: 0.18.1
  flutter_localizations:
    sdk: flutter

  # BLoC
  flutter_bloc: 8.1.3

  # Router
  go_router: ^10.0.0

  # Persisting
  shared_preferences: ^2.2.0

  # REST
  dio: ^5.3.2

  # Logging
  logging: ^1.2.0

  # Utils
  bloc_concurrency: 0.2.2
  path: ^1.8.2
  path_provider: ^2.0.12


  # Local packages
  rest_client:
    path: packages/rest_client

  # Widgets
  table_calendar: ^3.0.9
  image_picker: ^1.0.4

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Codegen
  build_runner: 2.4.6
  flutter_gen_runner: 5.3.1
  intl_utils: 2.8.4

  # Lints
  flutter_lints: ^2.0.0
  meta: ^1.9.1

  # Splash & launcher icon
  flutter_native_splash: ^2.2.0+1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_black.png"

flutter_native_splash:
  image: assets/images/logo_black.png
  color: "#FFFFFF"

flutter:
  uses-material-design: true

  generate: false

  shaders:
    - assets/shaders/shimmer.frag
  assets:
    - assets/images/
  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Geologica
      fonts:
        - asset: assets/fonts/Geologica-Light.ttf
          weight: 300
        - asset: assets/fonts/Geologica-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geologica-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/src/common/assets/generated
  line_length: 80

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: ru
  arb_dir: lib/src/common/localization/translations
  output_dir: lib/src/common/localization/generated
